language: java
branches:
  only:
    - dev_4_0
    - dev_5_0
    - dev_5_1
env:
  global:
    - secure: "FhQxNU0O4aylgoJDK6ymEjYc3ILFl4IjjrPx7OdCeG+UMqBc9da/0CM/l6ehWHHxn0VQUc0+7qZgQjguRdMRGVApMIxY2a9vipYnG6DwYKQD59oqoJHfTAqtb+50vdC85pyNiBIetraOdyfJfjVTmAgXRTUwW5GdgSklJFsqjIY="
    - secure: "PYwpkDwhGfQgIF9axubaKo6zuDxl+PF3zKc86SRxnGTk7bNYd5NFMBP1IAq4oBe0TgujC6fc4lH3Od6FpIy3PcFuRHpQaSwg8r5ZvyvNqGVlglyOitLKoLnByXDUkmATPKyMZDnVvPepGLs/6lsw9yjlO881Wy00JWYGHP2iWM8="
before_install: 'mvn -version'
install: 'mvn -U -B -e clean deploy -DskipTests'
